
While you may get an error like one shown below, you could ignore the error which does not affect the simulation.
If you find a way to solve this error, please let me know.

.conda/envs/alm/lib/python3.8/site-packages/pymatgen/io/vasp/sets.py:126: BadInputSetWarning: POTCAR data with symbol Ga_d is not known by pymatgen to                    correspond with the selected potcar_functional PBE. This POTCAR                    is known to correspond with functionals ['PBE_54', 'unvie_PBE_52', 'PBE_52']. Please verify that                    you are using the right POTCARs!
  warnings.warn(

